### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by Leejjon** [Baeldung/stackify#12]
This project is being used in the following guide:
https://stackify.com/guide-docker-java/#wpautbox_about

When I clone this project, cd into the spring-boot-app directory, I can run it with `mvn clean install spring-boot:run`

However, the tutorial tells me to run:
`java -Dspring.profiles.active=default -jar target/spring-boot-ops.war`

The war file that is generated with a maven build will be spring-boot-app-0.0.1-SNAPSHOT.war, but ok I changed that. When running the command:
`java -Dspring.profiles.active=default -jar target/spring-boot-app-0.0.1-SNAPSHOT.war`

I get:
`no main manifest attribute, in target/spring-boot-app-0.0.1-SNAPSHOT.war`

**Comment by lor6** [comment]
Hi @Leejjon  Please check the readme here: https://github.com/Baeldung/stackify/tree/master/spring-boot-app that clarifies how to run the app. We've informed the stackify team to update the guide as well.

**Comment by Leejjon** [comment]
Thank you for updating!
