### ISSUE TITLE
sorted and findFirst() operations

### ISSUE THREAD

**Issue by moun3imy** [Baeldung/stackify#8]
Hey Eugen,
Sorry for opening issue here and thanks for your [blog post ](https://stackify.com/streams-guide-java-8/#wpautbox_about)about streams.
In your article you say : 
"_This means, in the example above, even if we had used findFirst() after the sorted(), the sorting of all the elements is done before applying the findFirst(). This happens because the operation cannot know what the first element is until the entire stream is sorted._"
and this is not true if for example the sorting method is bubble sort and the first element is in his permanent order, so I don't think sort will proceed in this case. What do you think about this ?

**Comment by Maiklins** [comment]
Hi @moun3imy!
sorted() prevents lazy evaluation of all intermediary operation before it's called, but not after.
Let's consider the following example:

```
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.IntUnaryOperator;
import java.util.stream.IntStream;

public class SortedStreamTest {

    public static void main(String[] argv) {

        final AtomicInteger mapCount = new AtomicInteger(0);
        IntUnaryOperator plus1 = i -> { mapCount.getAndIncrement(); return i + 1; };
        IntStream stream = IntStream.of(3, 5, 7, 10, 2, 6, 8);

        int firstElement = stream
                .map(plus1)
                //.sorted()
                //.map(plus1)
                .findFirst()
                .getAsInt();

        System.out.println(firstElement);
        System.out.println("Map count: " + mapCount.get());
    }
}
```

In the above example, the mapping operation plus1 is executed only once, so here we have lazy evaluation.
However, if we call sorted() after the mapping, the mapping is executed 7 times:
```
int firstElement = stream 
.map(plus1) 
.sorted() 
//.map(plus1) 
.findFirst() 
.getAsInt();
```
Whereas if we call the mapping after sorted(), it's evaluated only once:
```
int firstElement = stream 
//.map(plus1) 
.sorted() 
.map(plus1) 
.findFirst() 
.getAsInt();
```
The applied sorting algorithm depends on the type of stream:
no sorting is necessary for already sorted streams, e.g. SortedSet
for non-parallel streams, Arrays.sort() is used
for non-parallel streams, Arrays.parallelSort() is used
The sort is executed completely.
